### ISSUE TITLE
https connection to artifactory not possible

### ISSUE THREAD

**Issue by faenschi** [JFrogDev/nexus2artifactory#10] opened 2017-08-22 11:57 UTC
hi all

i cannot connect to my artifactory instance via https:
```

2017-08-22 13:53:25,763 [MainThread] [INFO] (nex2art.menu.Setup:53) - Sending request to https://artifactory.blabla.bl/artifactory/api/system/ping.
2017-08-22 13:53:26,591 [MainThread] [ERROR] (nex2art.menu.Setup:63) - Error connecting to Artifactory:
Traceback (most recent call last):
  File "E:\apps\nexus2artifactory\nex2art\menu\Setup.py", line 56, in pingserver
    resp = urllib2.urlopen(req)
  File "E:\apps\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "E:\apps\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "E:\apps\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "E:\apps\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "E:\apps\Python27\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "E:\apps\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
2017-08-22 13:53:26,592 [MainThread] [INFO] (nex2art.menu.Setup:84) - System ping completed, status: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661).
```

any ideas?
regards angela

**Comment by DarthFennec** [comment] 2017-08-22 18:16
Looks like you're probably using a self-signed certificate. I've just pushed an update, now you can disable SSL verification by passing the `-s` option on the command line. Let me know if you have any other trouble.

**Comment by sellers** [comment] 2018-05-17 20:29
I can confirm it is working with an AWS provided certificate on an ELB fronting the installation.

**Comment by andreatera** [comment] 2019-05-15 06:45
@DarthFennec in my case I have Nexus3 instance under a self-signed certificate and I get the following error (even if I specified -s option):
``` plain text
2019-05-15 08:42:57,926 [MainThread] [INFO] (nex2art.core.Nexus3:193) - Sending request to https://172.16.8.112:9001/service/metrics/ping.
2019-05-15 08:42:57,944 [MainThread] [ERROR] (nex2art.core.Nexus3:208) - Error connecting to Nexus:
Traceback (most recent call last):
  File "/data/git/nexus2artifactory/nex2art/core/Nexus3.py", line 201, in queryNexus
    else: resp = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>
2019-05-15 08:42:57,944 [MainThread] [INFO] (nex2art.core.Nexus3:224) - System ping completed, status: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618).
2019-05-15 08:42:57,946 [MainThread] [INFO] (nex2art.core.Format:124) - Updating data tree with Nexus data.
2019-05-15 08:42:57,946 [MainThread] [INFO] (nex2art.core.Validate:24) - Validating tree from '/Initial Setup/Nexus Username'.

```

**Comment by andreatera** [comment] 2019-05-26 19:22
The only workaround I found is launching the script like this:
``` bash
 PYTHONHTTPSVERIFY=0 python NexusToArtifactory.py
```

**Comment by peters95** [comment] 2020-12-23 16:29
Closing issue due to age

**Closed as completed by peters95** 2020-12-23 16:29 UTC
