### ISSUE TITLE
dockerinfo missing

### ISSUE THREAD

**Issue by jspoth** [JFrogDev/nexus2artifactory#24] opened 2018-05-22 00:02 UTC
Hi,
I am trying to migrate a docker repo and noticed that once the migration completed...my docker images dont have "docker-info" tab populated on the UI.
Any suggestions why that would be happening?
Thanks

**Comment by guidograzioli** [comment] 2018-05-22 12:41
Reproducing same behaviour, docker info missing, can't pull the image (getting 'unsupported metadata version 2'). Pulling the same image from nexus, retagging and pushing to artifactory works.
Also, xray seems not to scan any images migrated from nexus.

**Comment by jspoth** [comment] 2018-05-22 16:00
When I try to pull the image i get "invalid reference format"

**Comment by DarthFennec** [comment] 2018-05-22 17:32
Hmm ... is your Nexus repo using Docker V1? The tool doesn't currently support V1, but it should work fine with V2.

Beyond that, if you could give an example of what your repository looks like in Nexus and in Artifactory (file layout, metadata content, properties, etc) that would probably be helpful.

**Comment by jspoth** [comment] 2018-05-22 18:12
the v1enabled flag is set to false , 'layout': 'simple-default'. From the properties file for one of the images ... blobStore.blob-name=v2/....
On the artifactory side after migration ... manifest type: application/vnd.docker.distribution.manifest.v2 json
Does the  above info help in debugging the issue further?
Thanks

**Comment by DarthFennec** [comment] 2018-05-22 21:25
Apologies, I wasn't clear; by "file layout" I meant "how are the files laid out". In Nexus, there should be a `v2/-/blobs/` folder with sha256 blobs in it, and manifest files are at `v2/<image>/manifests/<tag>`. In Artifactory the structure should be different: each image is an `<image>/<tag>/` folder, containing a `manifest.json` and a number of sha256 blobs. I wanted to see if your directory structures match what is expected.

You say that your manifest files have a "manifest type" property. Is that the only property they have? The tool should be adding the following three properties to every manifest file:

```
docker.repoName: <image>
docker.manifest: <tag>
docker.manifest.type: application/vnd.docker.distribution.manifest.v2+json
```

The image won't work if any of these are missing or wrong.

**Comment by mgetto** [comment] 2018-12-04 12:43
Hi, I'm facing the same issue.

> Reproducing same behaviour, docker info missing, can't pull the image (getting 'unsupported metadata version 2'). Pulling the same image from nexus, retagging and pushing to artifactory works.
Also, xray seems not to scan any images migrated from nexus.

This is all true for me as well.

I compared the manifest properties and noticed a difference. Instead of
`docker.manifest.type: application/vnd.docker.distribution.manifest.v2+json`
the following property is generated:
`docker.manifest.type: application/vnd.docker.distribution.manifest.v2 json`

When I manually change the property and replace the space with a plus sign it starts to work.
However I don't want to do this for every image by hand. Am I doing something wrong? Or is this a bug? If it is, is there a workaround?

Thanks

**Comment by mgetto** [comment] 2018-12-04 13:52
Ok, I found a workaround myself. By setting the property to the correct value with the jfrog cli:

`jfrog rt sp "<repo>/*/*manifest.json" "docker.manifest.type=application/vnd.docker.distribution.manifest.v2+json`

After this command everything seems to work as expected.

**Comment by DarthFennec** [comment] 2018-12-04 18:50
Huh. The `+` sign in a URL is often used as shorthand for a space character (which would otherwise be encoded as `%20`). It appears that since that property value is being sent as a matrix parameter in the URL, something is seeing that `.v2+json` and changing it to a `.v2 json`.

This should not be happening. The thing is, the migrator encodes the `+` to a `%2B`, which should prevent Artifactory or anything else from seeing it as anything but a literal `+`. As far as I know, if some service is still seeing it as a space character, there's nothing the migrator can do to change that service's mind.

I doubt Artifactory is doing this, since if it were, this issue would affect everyone. It seems more likely that some sort of proxy or load balancer or other intermediate service is making this translation, before the request reaches Artifactory.

**Comment by peters95** [comment] 2020-12-23 16:24
closing this issue due to age

**Closed as completed by peters95** 2020-12-23 16:24 UTC
